### ISSUE TITLE
Add photo support

### ISSUE THREAD

**Issue by julisana** [julisana/laravel-recipes#12]
- [ ] How to save in database
      - Associate with specific recipe
      - Associate with specific direction ?
- [ ] Where to physically save file. Database? Local Machine? S3?

**Comment by lriggle-strib** [comment]
Photo/File support added. They are saved in the same table, `Files`, but are differentiated by type.

**Comment by julisana** [comment]
Photo/File support added. They are saved in the same table, `Files`, but are differentiated by type.
